---
slurm_packages:
  - slurmd
  - libpmi

slurm_role: compute

install_packages: []

mpi_packages:
  oracle:
    - mpich
    - openmpi
  google:
    - mpich
    - openmpi
  aws: []

monitoring_role: client

admin_key_path: /root/citc_authorized_keys

ldap_hostname: "{{ ansible_local.citc.ldap_hostname }}"
