---
slurm_packages:
  - slurmd
  - pmi

slurm_role: compute

install_packages: []

mpi_packages:
  oracle:
    - mpich
    - openmpi
  google:
    - mpich
    - openmpi
  aws:
    - mpich
    - openmpi

monitoring_role: client

ldap_hostname: "{{ ansible_local.citc.ldap_hostname }}"
