# Install 389-ds

- name: enable 389-ds module
  command:
    cmd: dnf module enable -y 389-ds:1.4
  register: dnf_result
  changed_when: '"Nothing to do" not in dnf_result.stdout'

- name: install 389-ds
  package:
    name: 389-ds-base

- name: check if 389 setup already run
  command: systemctl list-unit-files dirsrv@.service  # noqa 301 303
  register: dirsrv_unit_list

- name: copy 389 config template
  template:
    src: ds389.inf.j2
    dest: /root/389ds.inf
  when: "'disabled' in dirsrv_unit_list.stdout"

- name: run dscreate
  command: dscreate from-file /root/389ds.inf
  when: "'disabled' in dirsrv_unit_list.stdout"

- name: start dirsrv
  service:
    name: "dirsrv@{{ mgmt_hostname }}"
    state: started

- include_tasks: tls.yml

- name: Wait for LDAP server to be ready
  wait_for:
    host: "{{ mgmt_hostname }}"
    port: 389

- name: ensure people OU exists
  ldap_entry:
    dn: ou=People,dc=citc,dc=acrc,dc=bristol,dc=ac,dc=uk
    objectClass:
      - top
      - organizationalUnit
    bind_dn: cn=Directory Manager
    bind_pw: "{{ ldap_dm_password }}"
    server_uri: "ldap://{{ mgmt_hostname }}"
  notify: restart dirsrv

- meta: flush_handlers
