---
#
# This is the one file that violates my rule of "don't just throw a bunch of
# stuff into a role." These are all really useful tools, with single line
# installs
#

- name: yum install <cool-stuff>
  yum:
    name:
      - curl
      - htop
      - iotop
      - lsof
      - rsync
      - screen
      - sysstat
      - tcpdump
      - traceroute
      - wget
      - nmap
      - git
      - cmake

- name: yum install packages
  yum:
    name: "{{ install_packages }}"
